import { createGoal, createProofState, type ProofState } from "./proofState";
import { parseContext, parseEquation } from "./parser";
import { runTactic } from "./tactics";

export interface ProofExample {
  id: string;
  title: string;
  summary: string;
  explanation: string;
  contextText: string;
  goalText: string;
  tacticText: string;
  provesWithTactic?: boolean;
}

const adjunctionContext = `category C
category D

object X : C
object X2 : C
object Y : D

functor F : C -> D
functor G : D -> C

adjunction adj : F -| G

morphism f : F X -> Y
morphism u : X -> X2`;

const verticalCompositeContext = `category C
category D

functor F : C -> D
functor G : C -> D
functor H : C -> D

nattrans alpha : F => G
nattrans beta : G => H

object X : C
object Y : C

morphism f : X -> Y`;

const productContext = `category C

object W : C
object X : C
object A : C
object B : C

product P of A B

morphism h : W -> X
morphism f : X -> A
morphism g : X -> B`;

export const proofExamples: ProofExample[] = [
  {
    id: "vertical-composite-naturality",
    title: "Split naturality rectangle",
    summary: "Proves naturality of beta after alpha by splitting the outer rectangle into two naturality squares.",
    explanation:
      "The initial diagram is only the outer goal. Add the auxiliary middle arrow G.map(f) from G X to G Y, select the two naturality squares as subgoals, prove them with naturality alpha at f and naturality beta at f, then close the outer goal by pasting.",
    contextText: verticalCompositeContext,
    goalText: "F.map(f) >> alpha_Y >> beta_Y = alpha_X >> beta_X >> H.map(f)",
    tacticText: "naturality alpha at f",
    provesWithTactic: false
  },
  {
    id: "transpose-counit",
    title: "Transpose then untranspose",
    summary: "Shows that transposing f : F X -> Y and then untransposing gives f back.",
    explanation:
      "The term eta(adj, X) >> G.map(f) is the transpose of f. Applying F.map to it and then composing with eps(adj, Y) untransposes it. When you click Prove, the try tactic first normalizes F.map over composition, rewrites the counit naturality square for f, then uses the left triangle identity to reduce the remaining eta/eps pair to an identity. The final normalized equation is f = f.",
    contextText: adjunctionContext,
    goalText: "F.map(eta(adj, X) >> G.map(f)) >> eps(adj, Y) = f",
    tacticText: "try"
  },
  {
    id: "product-pairing-precompose",
    title: "Pairing after precomposition",
    summary: "Proves that precomposing a pairing is the pairing of the precomposed maps.",
    explanation:
      "The product_ext P tactic proves equality of maps into the chosen product P by composing both sides with pi1(P) and pi2(P). Each projected goal then simplifies using the product projection rules, reducing both projections to h >> f and h >> g respectively.",
    contextText: productContext,
    goalText: "h >> <f, g> = <h >> f, h >> g>",
    tacticText: "product_ext P",
    provesWithTactic: false
  },
  {
    id: "left-triangle",
    title: "Left triangle identity",
    summary: "Checks the triangle identity F.map(eta_X) >> eps_{F X} = id_{F X}.",
    explanation:
      "This is one of the two triangle identities generated by an adjunction declaration. The simp tactic applies that generated rule directly.",
    contextText: adjunctionContext,
    goalText: "F.map(eta(adj, X)) >> eps(adj, F X) = id(F X)",
    tacticText: "simp"
  },
  {
    id: "right-triangle",
    title: "Right triangle identity",
    summary: "Checks the triangle identity eta_{G Y} >> G.map(eps_Y) = id_{G Y}.",
    explanation:
      "This is the other triangle identity generated by the adjunction. The simp tactic applies the generated right-triangle rule.",
    contextText: adjunctionContext,
    goalText: "eta(adj, G Y) >> G.map(eps(adj, Y)) = id(G Y)",
    tacticText: "simp"
  },
  {
    id: "counit-naturality",
    title: "Counit naturality",
    summary: "Checks the naturality square for the counit at f.",
    explanation:
      "The context contains f : F X -> Y. The adjunction generates the counit naturality rewrite for f, and simp applies it.",
    contextText: adjunctionContext,
    goalText: "F.map(G.map(f)) >> eps(adj, Y) = eps(adj, F X) >> f",
    tacticText: "simp"
  },
  {
    id: "unit-naturality",
    title: "Unit naturality",
    summary: "Checks the naturality square for the unit at u.",
    explanation:
      "The context contains u : X -> X2. Unit naturality is generated, but not tagged as simp, so this example uses an explicit rewrite command: rw adj.unitNaturality.u.",
    contextText: adjunctionContext,
    goalText: "u >> eta(adj, X2) = eta(adj, X) >> G.map(F.map(u))",
    tacticText: "rw adj.unitNaturality.u"
  }
];

export function buildExampleState(example: ProofExample): ProofState {
  const context = parseContext(example.contextText);
  const equation = parseEquation(example.goalText, context);

  return createProofState(context, [createGoal("goal-1", equation)]);
}

export function runExample(example: ProofExample): ProofState {
  const state = buildExampleState(example);
  const activeGoalId = state.activeGoalId;
  if (!activeGoalId) {
    throw new Error("Example did not create an active goal.");
  }

  return runTactic(state, activeGoalId, example.tacticText).state;
}
